flowchart TD
    A(Start of Round) --> B{Family Member Buzzes}
    B --> C[First to Buzz]
    C -->|Yes| D[Answers]
    C -->|No| OtherFamilyChance[Chance to Other Family's Member]

    subgraph RoundStart
        D --> CheckResponse{Is Response on Board?}
        CheckResponse -->|Yes| CompareAnswer[Check if Answer is Highest]
        CompareAnswer -->|Yes| FamilyContinues[Family Continues Answering]
        CompareAnswer -->|No| OtherFamilyChance
        CheckResponse -->|No| OtherFamilyChance
    end

    subgraph OtherFamilyRespondingAtStart
        OtherFamilyChance --> OtherMemberAnswers[Answers]
        OtherMemberAnswers --> CheckNewResponse{Is New Response on Board?}
        CheckNewResponse -->|Yes| CompareNewAnswer[Check if New Answer is Higher]
        CompareNewAnswer -->|Yes| NewFamilyContinues[New Family Continues Answering]
        CompareNewAnswer -->|No| FamilyContinues
        CheckNewResponse -->|No| NextBuzz[Next 2 Family Members to Buzz]
    end