name: Build Cython Modules

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
      - name: Build the Cython extension for Linux
        run: python setup.py
      - name: Upload Linux binaries
        uses: actions/upload-artifact@v2
        with:
          name: linux-binaries
          path: src/prec/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython
      - name: Build the Cython extension for Windows
        run: python setup.py
      - name: Upload Windows binaries
        uses: actions/upload-artifact@v2
        with:
          name: windows-binaries
          path: src/prec/
