name: Build Cython Modules

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install cython setuptools
      - name: Delete existing binaries
        run: rm src/prec/*
      - name: Build the Cython extension for Linux
        run: python setup.py
      - name: Configure Git (Linux)
        run: git config --global user.name "github-actions-Ubuntu"
      - name: Configure Git Email (Linux)
        run: git config --global user.email "github-actions@github.com"
      - name: Pull before push
        run: git pull
      - name: Add Linux binaries
        run: git add src/prec/*
      - name: Commit Linux binaries
        run: git commit -m "Add Linux binaries"
      - name: Push Linux binaries
        run: git push

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install cython setuptools
      - name: Delete existing binaries
        run: del src\prec\*
      - name: Build the Cython extension for Windows
        run: python setup.py
      - name: Configure Git (Windows)
        run: git config --global user.name "github-actions-Windows"
      - name: Configure Git Email (Windows)
        run: git config --global user.email "github-actions@github.com"
      - name: Pull before push
        run: git pull
      - name: Add Windows binaries
        run: git add src\prec\*
      - name: Commit Windows binaries
        run: git commit -m "Add Windows binaries"
      - name: Push Windows binaries
        run: git push
