name: Package Familiada App with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      # Step to create a flat directory for carrying output files
      - name: Create output directory
        run: mkdir flat

      # Step to move compiled Windows binaries
      - name: Move Windows binaries
        run: mv src/dist/windows/* flat/

      # Step to move data file
      - name: Move data file
        run: mv dane.csv flat/
    
      # Update artifact upload to new flat directory
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Familiada
          path: flat
          compression-level: 0
