name: Package Familiada App with Pyinstaller

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      # Step to create a flat directory for carrying output files
      - name: Create output directory
        run: mkdir familiada

      # Step to move compiled Windows binaries
      - name: Move Windows binaries
        run: mv src/dist/windows/* familiada/

      # Step to move data file
      - name: Move data file
        run: mv dane.csv familiada/

      # Step to zip the flat folder
      - name: Zip output folder
        run: zip -r familiada.zip familiada

      # Step to create a release and upload the zipped folder as an asset
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: familiada.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
